import csv

# Data to write to CSV
data = [
    ["role", "name", "title", "company", "description"],
    ["seller", "John Doe", "Sales Manager", "TechCorp", "TechCorp is a technology solutions provider"],
    ["buyer", "Jane Smith", "Procurement Officer", "HealthPlus", "HealthPlus is a healthcare services company"],
    ["seller", "Alice Brown", "Account Executive", "InnovateX", "InnovateX specializes in innovative software solutions"],
    ["buyer", "Bob White", "Head of Procurement", "MediCare", "MediCare offers comprehensive healthcare services"],
    ["seller", "Charlie Green", "Sales Director", "SmartTech", "SmartTech provides smart home devices"],
    ["buyer", "Eve Black", "Supply Chain Manager", "FitnessPlus", "FitnessPlus is a chain of fitness centers"],
    ["seller", "Dave Clark", "Business Development Manager", "NetSolutions", "NetSolutions offers networking solutions"],
    ["buyer", "Fay Blue", "Procurement Specialist", "HealthGuard", "HealthGuard provides health insurance services"],
    ["seller", "Grace Harris", "Sales Consultant", "DataWave", "DataWave offers data analytics solutions"],
    ["buyer", "Hank Yellow", "Procurement Coordinator", "WellnessWorks", "WellnessWorks provides wellness programs"],
    ["seller", "Ivy Adams", "Senior Sales Representative", "CloudNet", "CloudNet offers cloud computing services"],
    ["buyer", "Jack Orange", "Procurement Manager", "LifeCare", "LifeCare provides home healthcare services"],
    ["seller", "Karen White", "Account Manager", "TechVerse", "TechVerse specializes in virtual reality solutions"],
    ["buyer", "Leo Red", "Senior Buyer", "HealthCorp", "HealthCorp provides healthcare management services"],
    ["seller", "Mike Black", "Regional Sales Manager", "InnovateTech", "InnovateTech offers advanced tech solutions"],
    ["buyer", "Nina Green", "Head of Procurement", "FitLife", "FitLife provides fitness equipment and services"],
    ["seller", "Oscar Brown", "National Sales Manager", "SoftWave", "SoftWave develops software solutions for businesses"],
    ["buyer", "Paul White", "Procurement Analyst", "HealthPlus", "HealthPlus offers health insurance and services"],
    ["seller", "Quinn Red", "Inside Sales Representative", "NextGenTech", "NextGenTech specializes in next-gen technology"],
    ["buyer", "Rita Yellow", "Lead Buyer", "WellnessHealth", "WellnessHealth provides health and wellness solutions"],
    ["seller", "Sam Green", "Sales Executive", "DataNet", "DataNet provides data networking solutions"],
    ["buyer", "Tina Blue", "Procurement Officer", "HealthFirst", "HealthFirst offers healthcare services and solutions"],
    ["seller", "Uma White", "Corporate Sales Manager", "InnovativeCorp", "InnovativeCorp offers innovative business solutions"],
    ["buyer", "Victor Red", "Procurement Lead", "FitPro", "FitPro offers professional fitness services"],
    ["seller", "Wendy Brown", "Field Sales Manager", "SmartSolutions", "SmartSolutions provides smart technology solutions"],
    ["buyer", "Xander Yellow", "Chief Procurement Officer", "HealthInnovate", "HealthInnovate offers innovative health services"],
    ["seller", "Yara Green", "Sales Associate", "TechWave", "TechWave specializes in wave technology solutions"],
    ["buyer", "Zack Blue", "Senior Procurement Specialist", "WellnessSolutions", "WellnessSolutions offers comprehensive wellness services"],
    ["seller", "Aaron Black", "Sales Lead", "CloudTech", "CloudTech offers cloud-based technology solutions"],
    ["buyer", "Beth Red", "Procurement Executive", "FitWell", "FitWell offers fitness and wellness services"],
    ["seller", "Casey White", "Sales Representative", "NetInnovate", "NetInnovate specializes in network innovation"],
    ["buyer", "Diana Yellow", "Head of Procurement", "HealthLife", "HealthLife provides comprehensive healthcare solutions"],
    ["seller", "Eli Green", "Account Executive", "SmartTech", "SmartTech offers smart home and tech solutions"],
    ["buyer", "Fiona Blue", "Procurement Coordinator", "WellnessCorp", "WellnessCorp offers wellness and health services"],
    ["seller", "Gary Brown", "Sales Consultant", "DataTech", "DataTech provides data technology solutions"],
    ["buyer", "Harry White", "Procurement Manager", "HealthServices", "HealthServices offers a range of healthcare services"],
    ["seller", "Ingrid Red", "Senior Sales Manager", "InnovativeSolutions", "InnovativeSolutions provides business innovation solutions"],
    ["buyer", "Jason Yellow", "Senior Procurement Officer", "FitCorp", "FitCorp offers fitness and corporate wellness services"],
    ["seller", "Kate Green", "Sales Manager", "NextGenInnovate", "NextGenInnovate specializes in innovative tech solutions"],
    ["buyer", "Larry Blue", "Procurement Analyst", "HealthPlus", "HealthPlus provides comprehensive health services"],
    ["seller", "Mona White", "Account Manager", "TechInnovate", "TechInnovate specializes in innovative tech solutions"],
    ["buyer", "Nate Red", "Head of Procurement", "WellnessHealth", "WellnessHealth offers health and wellness programs"],
    ["seller", "Olivia Brown", "Sales Executive", "CloudWave", "CloudWave offers cloud technology solutions"],
    ["buyer", "Peter Yellow", "Procurement Lead", "HealthPro", "HealthPro provides professional healthcare services"],
    ["seller", "Quincy Green", "Regional Sales Manager", "SmartNet", "SmartNet offers smart networking solutions"],
    ["buyer", "Rachel Blue", "Lead Buyer", "FitServices", "FitServices offers fitness and health services"],
    ["seller", "Steven White", "National Sales Manager", "DataInnovate", "DataInnovate specializes in data innovation solutions"],
    ["buyer", "Tracy Red", "Chief Procurement Officer", "WellnessInnovate", "WellnessInnovate offers innovative wellness solutions"],
    ["seller", "Alex Brown", "Sales Director", "AlphaTech", "AlphaTech provides cutting-edge tech solutions"],
    ["buyer", "Bella White", "Procurement Director", "MedLife", "MedLife offers medical equipment and services"],
    ["seller", "Chris Green", "Sales Manager", "EcoTech", "EcoTech specializes in eco-friendly technology"],
    ["buyer", "Derek Black", "Senior Buyer", "FitHealth", "FitHealth provides fitness and health products"],
    ["seller", "Elena Blue", "Account Executive", "HealthTech", "HealthTech develops healthcare technology solutions"],
    ["buyer", "Frank Yellow", "Procurement Officer", "LifeWell", "LifeWell offers wellness and life coaching services"],
    ["seller", "Georgia Red", "Sales Consultant", "InnovaWave", "InnovaWave provides innovative tech solutions"],
    ["buyer", "Holly Green", "Procurement Specialist", "MedCare", "MedCare offers comprehensive medical services"],
    ["seller", "Isaac White", "Sales Manager", "TechSolutions", "TechSolutions offers IT and tech services"],
    ["buyer", "Jamie Blue", "Head of Procurement", "HealthInnovate", "HealthInnovate provides health innovation solutions"],
    ["seller", "Kelsey Yellow", "Sales Lead", "DataCore", "DataCore specializes in data management solutions"],
    ["buyer", "Liam Black", "Procurement Coordinator", "FitSolutions", "FitSolutions offers fitness management services"],
    ["seller", "Mary Brown", "Sales Executive", "NetCore", "NetCore provides networking and IT solutions"],
    ["buyer", "Nick Green", "Procurement Manager", "WellnessPro", "WellnessPro offers professional wellness services"],
    ["seller", "Olivia White", "Account Manager", "CloudSolutions", "CloudSolutions offers cloud storage and services"],
    ["buyer", "Paula Red", "Senior Procurement Specialist", "HealthFirst", "HealthFirst provides primary healthcare services"],
    ["seller", "Quinn Blue", "Sales Director", "InnovateNet", "InnovateNet offers network innovation solutions"],
    ["buyer", "Roger Yellow", "Chief Procurement Officer", "FitWell", "FitWell provides fitness and wellness services"],
    ["seller", "Sophia Green", "Sales Consultant", "NextGenData", "NextGenData specializes in data innovation solutions"],
    ["buyer", "Terry White", "Lead Buyer", "WellnessCorp", "WellnessCorp provides corporate wellness programs"],
    ["seller", "Uma Brown", "Sales Manager", "SmartWave", "SmartWave provides smart technology solutions"],
    ["buyer", "Victor Blue", "Head of Procurement", "HealthNet", "HealthNet offers healthcare networking solutions"],
    ["seller", "Will Red", "Senior Sales Representative", "TechInnovate", "TechInnovate provides innovative technology solutions"],
    ["buyer", "Xena Yellow", "Procurement Specialist", "FitHealth", "FitHealth offers fitness and health services"],
    ["seller", "Yvonne Green", "Account Executive", "DataSolutions", "DataSolutions specializes in data management solutions"],
    ["buyer", "Zane White", "Procurement Analyst", "HealthGuard", "HealthGuard offers health insurance and services"],
    ["seller", "Amy Brown", "Sales Manager", "CloudNet", "CloudNet offers cloud computing solutions"],
    ["buyer", "Brandon Blue", "Procurement Coordinator", "FitLife", "FitLife offers fitness and lifestyle services"],
    ["seller", "Cara Green", "Sales Consultant", "TechInnovate", "TechInnovate specializes in tech innovation solutions"],
    ["buyer", "Douglas White", "Procurement Officer", "HealthTech", "HealthTech offers healthcare technology solutions"],
    ["seller", "Evan Red", "Sales Executive", "DataCore", "DataCore provides data management and solutions"],
    ["buyer", "Fiona Yellow", "Head of Procurement", "LifeWell", "LifeWell provides comprehensive wellness services"],
    ["seller", "George Black", "Account Manager", "SmartNet", "SmartNet offers smart networking solutions"],
    ["buyer", "Hailey Blue", "Senior Buyer", "FitPro", "FitPro offers professional fitness services"],
    ["seller", "Isabel Green", "Sales Director", "NextGenTech", "NextGenTech specializes in next-gen tech solutions"],
    ["buyer", "Jack White", "Procurement Specialist", "WellnessSolutions", "WellnessSolutions provides wellness programs"],
    ["seller", "Kyle Red", "Sales Lead", "InnovaWave", "InnovaWave provides innovative technology solutions"],
    ["buyer", "Laura Yellow", "Procurement Manager", "HealthInnovate", "HealthInnovate offers innovative health solutions"],
    ["seller", "Mark Blue", "Senior Sales Manager", "TechSolutions", "TechSolutions offers IT and tech solutions"],
    ["buyer", "Nancy Green", "Lead Buyer", "WellnessHealth", "WellnessHealth provides health and wellness programs"],
    ["seller", "Oscar White", "Sales Consultant", "DataInnovate", "DataInnovate specializes in data innovation solutions"],
    ["buyer", "Paige Black", "Procurement Executive", "FitLife", "FitLife offers fitness and lifestyle services"],
    ["seller", "Quinn Red", "Account Manager", "SmartWave", "SmartWave provides smart technology solutions"],
    ["buyer", "Rachel Yellow", "Procurement Officer", "HealthCorp", "HealthCorp offers healthcare management services"],
    ["seller", "Sam Blue", "Sales Director", "InnovateNet", "InnovateNet specializes in network innovation solutions"],
    ["buyer", "Tom Green", "Head of Procurement", "FitSolutions", "FitSolutions provides fitness and wellness solutions"],
    ["seller", "Uma White", "Sales Executive", "TechCore", "TechCore offers technology and IT solutions"],
    ["buyer", "Victor Red", "Senior Buyer", "HealthFirst", "HealthFirst provides healthcare services"],
    ["seller", "Wendy Yellow", "Sales Lead", "DataWave", "DataWave offers data analytics solutions"],
    ["buyer", "Xander Blue", "Procurement Analyst", "WellnessWorks", "WellnessWorks provides wellness programs"],
    ["seller", "Yara Green", "Account Executive", "CloudNet", "CloudNet offers cloud computing services"],
    ["buyer", "Zack White", "Procurement Specialist", "LifeCare", "LifeCare provides home healthcare services"],
    # Add more data here
]

# Add 100 more rows of data
for i in range(100):
    if i % 2 == 0:
        data.append(["seller", f"Charlie Green {i}", f"Sales Director {i}", f"SmartTech {i}", f"SmartTech provides smart home devices {i}"])
    else:
        data.append(["buyer", f"Eve Black {i}", f"Supply Chain Manager {i}", f"FitnessPlus {i}", f"FitnessPlus is a chain of fitness centers {i}"])

# File path to save CSV
file_path = "profile.csv"

# Write data to CSV
with open(file_path, mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerows(data)

print("CSV file created successfully!")
